version: '3.7'

services:
  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
      target: base-with-sources
    entrypoint: ["npm", "run", "ci:test"]
  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
      target: base-with-sources
    entrypoint: ["npm", "run", "ci:test"]
